import jsPDF from "jspdf";

const generatePDF = ({
  totalWorkouts,
  totalMeals,
  caloriesBurned,
  caloriesConsumed,
}) => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text("Fitness & Health Tracking Report", 20, 20);

  doc.setFontSize(12);

  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 35);

  doc.text(`Total Workouts: ${totalWorkouts}`, 20, 50);
  doc.text(`Total Meals: ${totalMeals}`, 20, 60);
  doc.text(`Calories Burned: ${caloriesBurned}`, 20, 70);
  doc.text(`Calories Consumed: ${caloriesConsumed}`, 20, 80);

  doc.line(20, 90, 190, 90);

  doc.text(
    "Generated by Fitness & Health Tracking Application",
    20,
    105
  );

  doc.save("Fitness_Report.pdf");
};

export default generatePDF;